/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import patterns.Proxy.LoginFacade;

/**
 *
 * @author USER
 */
public class formLogin extends javax.swing.JFrame {

    /**
     * Creates new form VAdministradores
     */
    public formLogin() {
        initComponents();
        setTitle("Inicia sesión");
        setLocationRelativeTo(null);
        //setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        panel1_jpnl = new javax.swing.JPanel();
        usuario_lbl = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        separatorUsuario_spt = new javax.swing.JSeparator();
        contrasenha_lbl = new javax.swing.JLabel();
        psw_contrasenha = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        panel1_jpnl.setBackground(new java.awt.Color(255, 255, 255));
        panel1_jpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usuario_lbl.setForeground(new java.awt.Color(0, 0, 0));
        usuario_lbl.setText("Usuario:");
        panel1_jpnl.add(usuario_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 320, 20));

        txt_usuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_usuario.setForeground(new java.awt.Color(0, 0, 0));
        txt_usuario.setBorder(null);
        panel1_jpnl.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 320, 30));
        panel1_jpnl.add(separatorUsuario_spt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 320, 10));

        contrasenha_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contrasenha_lbl.setForeground(new java.awt.Color(0, 0, 0));
        contrasenha_lbl.setText("Contraseña:");
        panel1_jpnl.add(contrasenha_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 320, 20));
        contrasenha_lbl.getAccessibleContext().setAccessibleDescription("");

        psw_contrasenha.setBackground(new java.awt.Color(255, 255, 255));
        psw_contrasenha.setForeground(new java.awt.Color(0, 0, 0));
        psw_contrasenha.setBorder(null);
        panel1_jpnl.add(psw_contrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 320, 30));
        panel1_jpnl.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 320, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Escritorio\\Iconos\\persona.png")); // NOI18N
        jLabel1.setText("Login");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1_jpnl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, 100));

        salir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(0, 0, 0));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Escritorio\\Iconos\\close2.png")); // NOI18N
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        panel1_jpnl.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 50, 40));

        btn_ingresar.setBackground(new java.awt.Color(0, 102, 204));
        btn_ingresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresar.setText("Ingresar");
        btn_ingresar.setBorder(null);
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        panel1_jpnl.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 320, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 140;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(panel1_jpnl, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        String usuario = txt_usuario.getText();
        String contrasenha = psw_contrasenha.getText();
        LoginFacade login = new LoginFacade();
        if (!login.iniciarSesion(usuario, contrasenha)) {
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas, intente otra vez", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            formMenu ir = formMenu.getInstance();
            ir.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel contrasenha_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel1_jpnl;
    private javax.swing.JPasswordField psw_contrasenha;
    private javax.swing.JLabel salir;
    private javax.swing.JSeparator separatorUsuario_spt;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JLabel usuario_lbl;
    // End of variables declaration//GEN-END:variables
}
